version: '3'
services:
  nginx:
    depends_on: 
      - server
    build: ./nginx
    ports:
      - '8080:80'
    volumes:
      - ./client/tcx/dist:/var/www/html
      - ./nginx/server.conf:/etc/nginx/nginx.conf
    environment: 
      TZ: "Asia/Tokyo"

  server:
    depends_on: 
      - db
    build: ./server
    ports:
      - '8888:8888'
    volumes:
      - ./server:/app
    environment: 
      TZ: "Asia/Tokyo"

  db:
    build:  ./db
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: TCX
      TZ: "Asia/Tokyo"